domain: "che.dev.net"
tlsSecretName: "tls-dev-net-wildcard"
ingressClassName: "traefik"

auth:
  oAuthClientName: "eclipse-che"
  oAuthSecret: ""
  identityProviderURL: "https://auth.dev.net/realms/master"
