apiVersion: v1
kind: Service
metadata:
  name: {{ include "ollama.fullname" . }}
  namespace: {{ include "ollama.namespace" . }}
  labels:
    {{- include "ollama.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ollama.service.type }}
  ports:
  - port: {{ .Values.ollama.service.port }}
    targetPort: {{ .Values.ollama.service.port }}
    protocol: TCP
    name: http
    {{- if eq .Values.ollama.service.type "NodePort" }}
    nodePort: {{ .Values.ollama.service.nodePort }}
    {{- end }}
  selector:
    {{- include "ollama.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
