{{- if .Values.customPgadmin.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgadmin-ingress
  namespace: {{ .Values.customPgadmin.namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/headers-customrequestheaders: "X-Forwarded-Proto: https"
spec:
  ingressClassName: traefik
  rules:
  - host: {{ .Values.customPgadmin.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pgadmin
            port:
              number: 80
  tls:
  - hosts:
    - {{ .Values.customPgadmin.ingress.host }}
    secretName: {{ .Values.customPgadmin.ingress.tlsSecretName }}
{{- end }}
