hostname: ipa.prod.net
realm: PROD.NET
domain: prod.net

# Name of a pre-existing Kubernetes secret with keys:
#   admin-password: <FreeIPA admin password>
#   ds-password:    <Directory Server password>
credentialsSecret: freeipa-credentials

image:
  repository: freeipa/freeipa-server
  tag: "fedora-40-4.12.2"
  pullPolicy: IfNotPresent

persistence:
  # Path on GlusterFS mount (mounted at /mnt/gluster on all worker nodes)
  glusterMountPath: /mnt/gluster/freeipa
  size: 10Gi

ingress:
  enabled: true
  className: traefik
  hostname: ipa.prod.net
  tlsSecret: tls-prod-net-wildcard

securityContext:
  privileged: true

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
