hostname: ipa.prod.net
realm: PROD.NET
domain: prod.net

# Name of a pre-existing Kubernetes secret with keys:
#   admin-password: <FreeIPA admin password>
#   ds-password:    <Directory Server password>
credentialsSecret: freeipa-credentials

image:
  repository: freeipa/freeipa-server
  tag: "fedora-40-4.12.2"
  pullPolicy: IfNotPresent

args:
  nohostdns: true
  nontp: true
  setupdns: false
  autoforwarders: true
  allowzoneoverlap: true
  sshtrustdns: false

persistence:
  enabled: true
  storageClass: "local-path-freeipa"
  annotations: {}
  accessModes:
    - ReadWriteOnce
  size: 10Gi

podSecurityContext:
  enabled: false

containerSecurityContext:
  enabled: true
  privileged: true

ingress:
  enabled: true
  className: traefik
  hostname: ipa.prod.net
  tlsSecret: tls-prod-net-wildcard

diagnosticMode:
  enabled: false
  command:
    - sleep
  args:
    - infinity

extraEnv: {}

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
