{{- if .Values.certa.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "certa.fullname" . }}
  namespace: {{ include "certa.namespace" . }}
  labels:
    {{- include "certa.labels" . | nindent 4 }}
    app.kubernetes.io/component: certa
  {{- with .Values.certa.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.certa.ingress.className }}
  ingressClassName: {{ .Values.certa.ingress.className }}
  {{- end }}
  {{- if .Values.certa.ingress.tls }}
  tls:
    {{- range .Values.certa.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.certa.ingress.hosts }}
    {{- range .Values.certa.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "certa.fullname" $ }}
                port:
                  number: {{ $.Values.certa.service.port }}
          {{- end }}
    {{- end }}
    {{- else if and .Values.subdomain .Values.domain }}
    - host: {{ printf "%s.%s" .Values.subdomain .Values.domain | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "certa.fullname" . }}
                port:
                  number: {{ .Values.certa.service.port }}
    {{- end }}
{{- end }}
